import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shiv Kumar Prajapat",
  description: "Generated by create next app",
  applicationName: "Portfolio",
  // referrer: "origin-when-cross-origin",
  keywords: ["Next.js", "React", "JavaScript"],
  authors: [{ name: "Shiv Kumar Prajapat", url: "https://nextjs.org" }],
  creator: "Shiv Kumar Prajapat",
  openGraph: {
    siteName: "Next.js",
    title: "Shiv Kumar Prajapat",
    description: "this is og test description",
    url: "https://www.youtube.com",
    // images: "https://nextjs.org/static/blog/next-14/twitter-card.png",
    locale: "en_US",
    type: "website",
    images: [
      {
        url: 'https://nextjs.org/static/blog/next-14/twitter-card.png',
        width: 800,
        height: 600,
      },
      {
        url: 'https://nextjs.org/static/blog/next-14/twitter-card.png',
        width: 1800,
        height: 1600,
        alt: 'My custom alt',
      },
    ],
  },
};
// export const viewport: Viewport = {
//   themeColor: "black",
//   width: "device-width",
//   initialScale: 1,
//   maximumScale: 1,
//   // Also supported by less commonly used
//   // interactiveWidget: 'resizes-visual',
// };
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
